### ISSUE TITLE
Bento Helm charts

### ISSUE THREAD

**Issue by jpetazzo** [warpstreamlabs/bento#121]
Hi!

First of all, thank you for continuing the open source development with Bento :)

Earlier this year, I used Benthos for a [live stream](https://youtu.be/b1MHCUcxcdU?si=2NLjW_6ftjnISlES&t=2010) showing how to autoscale Kubernetes workloads with message queues. (Sorry, the live stream is in French, but I thought I'd share the link anyway just in case anyone is curious :)).

Back then, we used helm charts that were at https://benthosdev.github.io/benthos-helm-chart/. It looks like these charts have now moved to https://benthosdev.github.io/charts/.

I was wondering if you had any plans to host similar Helm charts for Bento? (Perhaps they already exist and I missed them?)

I don't know exactly what was the release pipeline for these charts so I don't know how easy/hard it would be to have them for Bento, but I thought I'd ask.

Thank you!

**Comment by antmordel** [comment]
Interested on this.

**Comment by gregfurman** [comment]
Hey! Happy to announce that we've released a bento helm chart! You can find the repo over at [warpstreamlabs/bento-helm-chart](https://github.com/warpstreamlabs/bento-helm-chart).

Since we're overachievers, we have provided two options for installing the charts: through GitHub pages or the GitHub Container Registry.

Install via GitHub Pages:
```shell
helm repo add bento-helm https://warpstreamlabs.github.io/bento-helm-chart
helm repo update
helm install bento bento-helm/bento
```

Otherwise, feel free to point directly to the [GHCR package](https://github.com/orgs/warpstreamlabs/packages?repo_name=bento-helm-chart):
```shell
helm upgrade --install bento oci://ghcr.io/warpstreamlabs/bento-helm/bento --version 0.1.0
```

I've tested this against a K8s cluster on my local and all seems to be working fine. These charts are almost identical to their forked counterpart, only differing in some default name parameters/versions.

If you encounter any problems, do let us know! 🍱

**Comment by gregfurman** [comment]
@jpetazzo Happy to close this issue now that charts have been released?

**Comment by jpetazzo** [comment]
Yes, absolutely!

I've replaced benthos with bento in my stack (an example is visible on [that demo repo](https://github.com/jpetazzo/beyond-load-balancers/)) and all works well.

Thank you folks, you're the bestests <3
